"""sla_notification_baseline

Revision ID: 64ee01b62f75
Revises: c14dab63585a
Create Date: 2026-06-24 11:54:56.537248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64ee01b62f75'
down_revision: Union[str, Sequence[str], None] = 'c14dab63585a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS sla")
    op.execute("CREATE SCHEMA IF NOT EXISTS notification")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_calendars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('working_days', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='sla'
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='notification'
    )
    op.create_index(op.f('ix_notification_notifications_user_id'), 'notifications', ['user_id'], unique=False, schema='notification')
    op.create_table('holidays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calendar_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['sla.business_calendars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sla'
    )
    op.create_index(op.f('ix_sla_holidays_date'), 'holidays', ['date'], unique=True, schema='sla')
    op.create_table('sla_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('work_item_type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('response_target_mins', sa.Integer(), nullable=False),
    sa.Column('resolution_target_mins', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['sla.business_calendars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='sla'
    )
    op.create_table('sla_clocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accumulated_active_mins', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('breached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_breached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_item.work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sla'
    )
    op.create_index('ix_sla_clocks_work_item_metric', 'sla_clocks', ['work_item_id', 'metric'], unique=False, schema='sla')
    # ### end Alembic commands ###

    # Seed Default Calendar
    op.execute(
        "INSERT INTO sla.business_calendars (id, name, timezone, working_days, start_time, end_time, is_default, created_at, updated_at) "
        "VALUES ('d3b07384-d113-4956-be7f-000000000001', 'Standard Business Hours', 'Asia/Kolkata', ARRAY[1,2,3,4,5], '09:00:00', '18:00:00', true, NOW(), NOW()) "
        "ON CONFLICT (name) DO NOTHING"
    )

    # Seed Default SLA Policies
    op.execute(
        "INSERT INTO sla.sla_policies (id, name, description, work_item_type, priority, response_target_mins, resolution_target_mins, calendar_id, created_at, updated_at) VALUES "
        "('d3b07384-d113-4956-be7f-000000000002', 'P1 Critical Incident Policy', 'Response target 15m, Resolution target 1h', 'incident', 'P1', 15, 60, 'd3b07384-d113-4956-be7f-000000000001', NOW(), NOW()), "
        "('d3b07384-d113-4956-be7f-000000000003', 'P2 High Incident Policy', 'Response target 30m, Resolution target 4h', 'incident', 'P2', 30, 240, 'd3b07384-d113-4956-be7f-000000000001', NOW(), NOW()), "
        "('d3b07384-d113-4956-be7f-000000000004', 'P3 Medium Incident Policy', 'Response target 60m, Resolution target 8h', 'incident', 'P3', 60, 480, 'd3b07384-d113-4956-be7f-000000000001', NOW(), NOW()), "
        "('d3b07384-d113-4956-be7f-000000000005', 'P4 Low Incident Policy', 'Response target 120m, Resolution target 16h', 'incident', 'P4', 120, 960, 'd3b07384-d113-4956-be7f-000000000001', NOW(), NOW()) "
        "ON CONFLICT DO NOTHING"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sla_clocks_work_item_metric', table_name='sla_clocks', schema='sla')
    op.drop_table('sla_clocks', schema='sla')
    op.drop_table('sla_policies', schema='sla')
    op.drop_index(op.f('ix_sla_holidays_date'), table_name='holidays', schema='sla')
    op.drop_table('holidays', schema='sla')
    op.drop_index(op.f('ix_notification_notifications_user_id'), table_name='notifications', schema='notification')
    op.drop_table('notifications', schema='notification')
    op.drop_table('business_calendars', schema='sla')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS sla CASCADE")
    op.execute("DROP SCHEMA IF EXISTS notification CASCADE")

