"""comments_attachments

Revision ID: 9dd98f2316cd
Revises: a003_incident_extension
Create Date: 2026-06-24 11:26:18.030555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dd98f2316cd'
down_revision: Union[str, Sequence[str], None] = 'a003_incident_extension'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_item.work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='work_item'
    )
    op.create_index(op.f('ix_work_item_attachments_uploaded_by_id'), 'attachments', ['uploaded_by_id'], unique=False, schema='work_item')
    op.create_index(op.f('ix_work_item_attachments_work_item_id'), 'attachments', ['work_item_id'], unique=False, schema='work_item')
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_item.work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='work_item'
    )
    op.create_index(op.f('ix_work_item_comments_author_id'), 'comments', ['author_id'], unique=False, schema='work_item')
    op.create_index(op.f('ix_work_item_comments_work_item_id'), 'comments', ['work_item_id'], unique=False, schema='work_item')
    op.alter_column('audit_logs', 'old_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='audit')
    op.alter_column('audit_logs', 'new_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='audit')
    op.alter_column('audit_logs', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='audit')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs', schema='audit')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs', schema='audit')
    op.drop_index(op.f('ix_audit_logs_entity_type_entity_id_created_at'), table_name='audit_logs', schema='audit')
    op.create_index(op.f('ix_audit_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False, schema='audit')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'AGENT', 'MANAGER', 'CHANGE_MANAGER', 'CAB_MEMBER', 'REQUESTER', name='userrole', native_enum=False),
               existing_nullable=False,
               schema='identity')
    op.alter_column('users', 'profile',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"),
               schema='identity')
    op.drop_index(op.f('ix_wi_assigned_group'), table_name='work_items', schema='work_item')
    op.drop_index(op.f('ix_wi_assigned_to'), table_name='work_items', schema='work_item')
    op.drop_index(op.f('ix_wi_display_id'), table_name='work_items', schema='work_item')
    op.drop_index(op.f('ix_wi_reported_by'), table_name='work_items', schema='work_item')
    op.drop_index(op.f('ix_wi_status'), table_name='work_items', schema='work_item')
    op.drop_index(op.f('ix_wi_type'), table_name='work_items', schema='work_item')
    op.drop_index(op.f('ix_wi_reported_by_created'), table_name='work_items', schema='work_item')
    op.create_index('ix_wi_reported_by_created', 'work_items', ['reported_by_id', 'created_at'], unique=False, schema='work_item')
    op.create_index(op.f('ix_work_item_work_items_assigned_group_id'), 'work_items', ['assigned_group_id'], unique=False, schema='work_item')
    op.create_index(op.f('ix_work_item_work_items_assigned_to_id'), 'work_items', ['assigned_to_id'], unique=False, schema='work_item')
    op.create_index(op.f('ix_work_item_work_items_display_id'), 'work_items', ['display_id'], unique=True, schema='work_item')
    op.create_index(op.f('ix_work_item_work_items_reported_by_id'), 'work_items', ['reported_by_id'], unique=False, schema='work_item')
    op.create_index(op.f('ix_work_item_work_items_status'), 'work_items', ['status'], unique=False, schema='work_item')
    op.create_index(op.f('ix_work_item_work_items_work_item_type'), 'work_items', ['work_item_type'], unique=False, schema='work_item')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_item_work_items_work_item_type'), table_name='work_items', schema='work_item')
    op.drop_index(op.f('ix_work_item_work_items_status'), table_name='work_items', schema='work_item')
    op.drop_index(op.f('ix_work_item_work_items_reported_by_id'), table_name='work_items', schema='work_item')
    op.drop_index(op.f('ix_work_item_work_items_display_id'), table_name='work_items', schema='work_item')
    op.drop_index(op.f('ix_work_item_work_items_assigned_to_id'), table_name='work_items', schema='work_item')
    op.drop_index(op.f('ix_work_item_work_items_assigned_group_id'), table_name='work_items', schema='work_item')
    op.drop_index('ix_wi_reported_by_created', table_name='work_items', schema='work_item')
    op.create_index(op.f('ix_wi_reported_by_created'), 'work_items', ['reported_by_id', sa.literal_column('created_at DESC')], unique=False, schema='work_item')
    op.create_index(op.f('ix_wi_type'), 'work_items', ['work_item_type'], unique=False, schema='work_item')
    op.create_index(op.f('ix_wi_status'), 'work_items', ['status'], unique=False, schema='work_item')
    op.create_index(op.f('ix_wi_reported_by'), 'work_items', ['reported_by_id'], unique=False, schema='work_item')
    op.create_index(op.f('ix_wi_display_id'), 'work_items', ['display_id'], unique=True, schema='work_item')
    op.create_index(op.f('ix_wi_assigned_to'), 'work_items', ['assigned_to_id'], unique=False, schema='work_item')
    op.create_index(op.f('ix_wi_assigned_group'), 'work_items', ['assigned_group_id'], unique=False, schema='work_item')
    op.alter_column('users', 'profile',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"),
               schema='identity')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'AGENT', 'MANAGER', 'CHANGE_MANAGER', 'CAB_MEMBER', 'REQUESTER', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='identity')
    op.drop_index(op.f('ix_audit_audit_logs_entity_type'), table_name='audit_logs', schema='audit')
    op.drop_index(op.f('ix_audit_audit_logs_entity_id'), table_name='audit_logs', schema='audit')
    op.create_index(op.f('ix_audit_logs_entity_type_entity_id_created_at'), 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False, schema='audit')
    op.alter_column('audit_logs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               schema='audit')
    op.alter_column('audit_logs', 'new_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               schema='audit')
    op.alter_column('audit_logs', 'old_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               schema='audit')
    op.drop_index(op.f('ix_work_item_comments_work_item_id'), table_name='comments', schema='work_item')
    op.drop_index(op.f('ix_work_item_comments_author_id'), table_name='comments', schema='work_item')
    op.drop_table('comments', schema='work_item')
    op.drop_index(op.f('ix_work_item_attachments_work_item_id'), table_name='attachments', schema='work_item')
    op.drop_index(op.f('ix_work_item_attachments_uploaded_by_id'), table_name='attachments', schema='work_item')
    op.drop_table('attachments', schema='work_item')
    # ### end Alembic commands ###
