"""change_approval_baseline

Revision ID: b426c5df7089
Revises: 64ee01b62f75
Create Date: 2026-06-24 12:43:27.819334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b426c5df7089'
down_revision: Union[str, Sequence[str], None] = '64ee01b62f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS change")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('change_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['change_id'], ['work_item.work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='change'
    )
    op.create_index('ix_change_approvals_change_approver', 'approvals', ['change_id', 'approver_id'], unique=True, schema='change')
    op.create_table('change_extensions',
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('expedited', sa.Boolean(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('implementation_plan', sa.Text(), nullable=True),
    sa.Column('backout_plan', sa.Text(), nullable=True),
    sa.Column('validation_plan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_item.work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_item_id'),
    schema='change'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_extensions', schema='change')
    op.drop_index('ix_change_approvals_change_approver', table_name='approvals', schema='change')
    op.drop_table('approvals', schema='change')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS change CASCADE")

