"""email_graph

Revision ID: c14dab63585a
Revises: 9dd98f2316cd
Create Date: 2026-06-24 11:43:54.582367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14dab63585a'
down_revision: Union[str, Sequence[str], None] = '9dd98f2316cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS email")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_quarantine',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='email'
    )
    op.create_index(op.f('ix_email_email_quarantine_message_id'), 'email_quarantine', ['message_id'], unique=False, schema='email')
    op.create_table('graph_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.String(length=100), nullable=False),
    sa.Column('mailbox', sa.String(length=255), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_state', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='email'
    )
    op.create_index(op.f('ix_email_graph_subscriptions_subscription_id'), 'graph_subscriptions', ['subscription_id'], unique=True, schema='email')
    op.create_table('email_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_item.work_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='email'
    )
    op.create_index(op.f('ix_email_email_messages_message_id'), 'email_messages', ['message_id'], unique=True, schema='email')
    op.create_index(op.f('ix_email_email_messages_work_item_id'), 'email_messages', ['work_item_id'], unique=False, schema='email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_email_messages_work_item_id'), table_name='email_messages', schema='email')
    op.drop_index(op.f('ix_email_email_messages_message_id'), table_name='email_messages', schema='email')
    op.drop_table('email_messages', schema='email')
    op.drop_index(op.f('ix_email_graph_subscriptions_subscription_id'), table_name='graph_subscriptions', schema='email')
    op.drop_table('graph_subscriptions', schema='email')
    op.drop_index(op.f('ix_email_email_quarantine_message_id'), table_name='email_quarantine', schema='email')
    op.drop_table('email_quarantine', schema='email')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS email CASCADE")
