export const STATE_MACHINES = {
  INCIDENT: {
    initial: 'new',
    states: ['new', 'assigned', 'in_progress', 'pending', 'resolved', 'closed'],
    transitions: {
      assign:         { from: 'new',        to: 'assigned',    roles: ['ADMIN', 'MANAGER'] },
      take_over:      { from: 'assigned',   to: 'in_progress', roles: ['AGENT'] },
      escalate:       { from: 'assigned',   to: 'assigned',    roles: ['MANAGER'], reassign: true },
      pending:        { from: 'in_progress', to: 'pending',    roles: ['AGENT'] },
      reconnect:      { from: 'pending',    to: 'in_progress', roles: ['AGENT'] },
      resolve:        { from: 'in_progress', to: 'resolved',   roles: ['AGENT'] },
      close:          { from: 'resolved',    to: 'closed',     roles: ['AGENT', 'MANAGER'] },
      reopen:         { from: 'resolved',    to: 'in_progress', roles: ['AGENT', 'MANAGER'] },
      reassign:       { from: '*',           to: 'assigned',   roles: ['MANAGER'] },
    },
  },
  SERVICE_REQUEST: {
    initial: 'new',
    states: ['new', 'assigned', 'in_progress', 'pending', 'resolved', 'closed'],
    transitions: {
      assign:         { from: 'new',        to: 'assigned',    roles: ['ADMIN', 'MANAGER'] },
      take_over:      { from: 'assigned',   to: 'in_progress', roles: ['AGENT'] },
      pending:        { from: 'in_progress', to: 'pending',    roles: ['AGENT'] },
      reconnect:      { from: 'pending',    to: 'in_progress', roles: ['AGENT'] },
      resolve:        { from: 'in_progress', to: 'resolved',   roles: ['AGENT'] },
      close:          { from: 'resolved',    to: 'closed',     roles: ['AGENT', 'MANAGER'] },
      reopen:         { from: 'resolved',    to: 'in_progress', roles: ['AGENT', 'MANAGER'] },
      reassign:       { from: '*',           to: 'assigned',   roles: ['MANAGER'] },
    },
  },
  CHANGE: {
    initial: 'new',
    states: ['new', 'assigned', 'planned', 'approved', 'in_progress', 'implemented', 'monitoring', 'closed'],
    transitions: {
      assign:         { from: 'new',        to: 'assigned',    roles: ['ADMIN', 'CHANGE_MANAGER'] },
      plan:           { from: 'assigned',   to: 'planned',     roles: ['CHANGE_MANAGER'] },
      submit:         { from: 'planned',    to: 'approved',    roles: ['CHANGE_MANAGER'] },
      reject:         { from: 'planned',    to: 'assigned',    roles: ['CHANGE_MANAGER'] },
      implement:      { from: 'approved',   to: 'in_progress', roles: ['AGENT'] },
      complete:       { from: 'in_progress', to: 'implemented', roles: ['AGENT'] },
      monitor:        { from: 'implemented', to: 'monitoring', roles: ['AGENT'] },
      close:          { from: 'monitoring',  to: 'closed',     roles: ['CHANGE_MANAGER'] },
      rollback:       { from: 'in_progress', to: 'assigned',   roles: ['CHANGE_MANAGER'] },
      reassign:       { from: '*',           to: 'assigned',   roles: ['ADMIN', 'CHANGE_MANAGER'] },
    },
  },
  PROBLEM: {
    initial: 'new',
    states: ['new', 'assigned', 'in_progress', 'pending', 'resolved', 'closed'],
    transitions: {
      assign:         { from: 'new',        to: 'assigned',    roles: ['ADMIN', 'MANAGER'] },
      take_over:      { from: 'assigned',   to: 'in_progress', roles: ['AGENT'] },
      pending:        { from: 'in_progress', to: 'pending',    roles: ['AGENT'] },
      reconnect:      { from: 'pending',    to: 'in_progress', roles: ['AGENT'] },
      resolve:        { from: 'in_progress', to: 'resolved',   roles: ['AGENT'] },
      close:          { from: 'resolved',    to: 'closed',     roles: ['AGENT', 'MANAGER'] },
      reopen:         { from: 'resolved',    to: 'in_progress', roles: ['AGENT', 'MANAGER'] },
      identify_change: { from: 'assigned',  to: 'in_progress', roles: ['AGENT'] },
      reassign:       { from: '*',           to: 'assigned',   roles: ['MANAGER'] },
    },
  },
}
